### ISSUE TITLE
新竹市與嘉義市區碼問題？

### ISSUE THREAD

**Issue by CoffieLeo** [yyc1217/twzipcode-vue#113]
不好意思，剛錯發在 twzipcode-data 了!!!!!!
不曉得新竹市跟嘉義市的區碼問題有解嗎？
看起來是兩個城市內的區碼都相同，所以下拉選單在選擇時都出現同一個區域

**Comment by ausir0726** [comment]
![image](https://user-images.githubusercontent.com/7247064/118083830-381fd580-b3f2-11eb-9c54-9cf811893a31.png)

**Comment by yyc1217** [comment]
See yyc1217/twzipcode-data#58

**Comment by yyc1217** [comment]
Solved in e2fca4a261db238e92231f661f18cf24262625e3
